### ISSUE TITLE
Create the form

### ISSUE THREAD

**Issue by ghost** [JescoInc/NotepadClone#1]
Create the basic form. It should include a textbox and a top menu.  Name both appropriately.  Add a menu item "File" to the top menu, and add "E&xit" item to the newly created file menu.

**Comment by RPDevJesco** [comment]
Added File and Exit to the top menu.

**Comment by ghost** [comment]
This objective is complete, however I am logging a few bug reports for it.  You have the option of handling the bugs before moving on to the next objective or save them for later.  Generally, it's advisable to handle bugs as soon as possible so they don't cause more problems down the road.
