### ISSUE TITLE
Don't store FileSaveDialog

### ISSUE THREAD

**Issue by ghost** [JescoInc/NotepadClone#10]
Instead of keeping a reference to the FileSaveDialog, store a string for the file's path.  The FileSaveDialog uses a bit more memory because it has a bunch of other values associated with it.

So move your definition of the FileSaveDialog back into the function where you need it.  At class level create a string called something like "CurrentFilePath".  This way, you can use string.IsNullOrEmpty(CurrentFilePath) to see if the file path has been set in the saving code, and if not have it call the SaveAs code instead.

Both Load, and SaveAs should set the value of the CurrentFilePath, and should not care what the value is otherwise.

**Comment by RPDevJesco** [comment]
Fixed, however the SaveAs function still has an UnauthorizedAccessException coursing through it.

**Comment by ghost** [comment]
You're saving the current path, but you should be saving the current file path.  The intent is to store the filename and it's path so that you can reuse that in the Save menu option so you don't have to ask the user where to save the file again.
