### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by ghost** [JescoInc/NotepadClone#11]
DRY is an acronym that stands for "Don't Repeat Yourself".  This isn't just about not re-writing the same function code, but is also about not rewriting something that could easily be a variable.

Take a look at your code for instance.  In both the saving and the loading you declare a filter string.  Since the actual value of the filter is the same in both cases, perhaps you could create

```
private const string FileFilter = "FILTER TEXT";
```

at class level and use that instead.  Then if you want to change the filter, you only have to change it in one place.

**Comment by RPDevJesco** [comment]
Fixed.
