### ISSUE TITLE
Menu option text not aligned

### ISSUE THREAD

**Issue by ghost** [JescoInc/NotepadClone#19]
The text for the menu options isn't properly aligned in the menu.  Some items appear as though they were sub items of the item above them, when they aren't.

**Comment by RPDevJesco** [comment]
Not sure which one you are referring to, When the Notepad clone is running, everything is centered appropriately.

**Comment by ghost** [comment]
Every notepad and windows program i've used doesn't center the menu text, it's all left aligned.

**Comment by RPDevJesco** [comment]
Changed alignment to left vs center.
