### ISSUE TITLE
Add File Loading

### ISSUE THREAD

**Issue by ghost** [JescoInc/NotepadClone#2]
Add a "&Load" menu item to the file menu.  When clicked it should display the OpenFileDialog to let the user select a file.  When the user clicks OK, the file should be opened and the contents of the file should be displayed in the texbox control on the form.

**Comment by RPDevJesco** [comment]
Load event created. And contents of file appropriately displays in the textbox. However, there is currently a bug when someone selects the cancel button or exits from the DialogBox, which throws an exception. Currently working on fixing the exception.

**Comment by RPDevJesco** [comment]
Bug has been fixed.

**Comment by ghost** [comment]
Loading is working.
