### ISSUE TITLE
Window doesn't resize well

### ISSUE THREAD

**Issue by ghost** [JescoInc/NotepadClone#5]
The window doesn't resize well.  If you drag the edge of the window out farther than the original design, the controls don't resize with the form so they stay in the top left corner.  Likewise, if you drag the edge of the window in, the controls don't resize with the form so parts of the controls end up being off the screen.

**Comment by RPDevJesco** [comment]
Currently working this bug to fix the issue.

**Comment by RPDevJesco** [comment]
Update, still working to resolve this bug. Shouldn't be too much longer now. I believe I have it all figured out on what is causing the issue.

**Comment by RPDevJesco** [comment]
Window cannot be resized at the moment to accommodate for my inability to fix the resizing issue.

**Comment by ghost** [comment]
There are multiple things you'll need to do to fix this.

First, you need to define the rows for the grid

```
        <Grid.RowDefinitions>
            <RowDefinition Height="auto"/>
            <RowDefinition/>
        </Grid.RowDefinitions>
```

Notice that i've defined two rows, with the height of the first one set to auto.  This will tell it to shring the first row down to fit it's contents, which will be the menu bar.

Next, remove height, width, and stretch definitions from all controls.  By default controls in WPF are set to auto-stretch to fill the grid cell they are contained in, but if you specify a height and width, they wont' stretch anymore.

Finally specify which cells the controls should be in.

Here's the WPF code for the form after I edit it to fix this issue:

```
<Window x:Class="NotepadClone.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="NotePad Clone" >
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="auto"/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Menu Grid.Row="0" >
            <MenuItem Header="File" Name="MenuFile">
                <MenuItem Header="Load" Name="MenuFileLoad" HorizontalAlignment="Center"/>
                <MenuItem Header="Save" Name="MenuFileSave" HorizontalAlignment="Center"/>
                <Separator/>
                <MenuItem Header="Exit" Name="MenuFileExit" />
            </MenuItem>
        </Menu>
        <TextBox Name="TxtBox" Grid.Row="1" TextWrapping="Wrap" Text="" Margin="3,3,3,3" SpellCheck.IsEnabled="True" IsManipulationEnabled="True" IsTabStop="False" AllowDrop="False" ClipToBounds="True" AcceptsReturn="True" AcceptsTab="True" Grid.RowSpan="2" />
    </Grid>
</Window>
```

Also note that I've moved the Exit menu item to be under file.  If you look any ANY windows application, that's where you will find the Exit menu option.

You may also note that I've changed the names of the menu and it's items.  It's pretty much standard to name the menu, and include the menu name in the menu's items.  By practice the name for each menu item should give a clear indication of where it is in the menu.

**Comment by RPDevJesco** [comment]
Fixed in project.

**Comment by ghost** [comment]
Works perfectly now.  Great job.
