### ISSUE TITLE
Control IDs?

### ISSUE THREAD

**Issue by ghost** [JescoInc/NotepadClone#6]
None of the controls have ids or names.  These will be needed later to work with the controls.  Its best practice to always assign an id or a name to every control when you create it.

**Comment by RPDevJesco** [comment]
All controls I will need access to have names as of now.

**Comment by ghost** [comment]
The only issue that I see with the naming is in the menu.  By general practice, you should give a name to each menu, and use that name in each of that menu's items.  The general rule of thumb is that the name of each menu item should clearly identify where it is in the menu.  See my response on the window resizing ticket for an example of what I mean.

If we were to have multiple menus then we'd have to name the menu bar as well, but since Notepad only has one menu, that's not an issue for us yet.

**Comment by ghost** [comment]
Bug fixed.
