### ISSUE TITLE
Textbox ignores certain inputs

### ISSUE THREAD

**Issue by ghost** [JescoInc/NotepadClone#7]
This should be relatively easy for you to fix.  The text box currently doesn't accept the Enter key or the Tab key.  It will need to accept both of these in order to fully clone the functionality of Notepad.

**Comment by RPDevJesco** [comment]
Text box now accepts the Return key and Tab key with intended text function results.

**Comment by ghost** [comment]
Unless you haven't pushed the changes back, I'm not seeing them.

**Comment by RPDevJesco** [comment]
Fixed it, should show up in latest push.

**Comment by ghost** [comment]
Excellent job. :)
