### ISSUE TITLE
Split the filter into seperate filters

### ISSUE THREAD

**Issue by ghost** [JescoInc/NotepadClone#9]
Instead of just one filter for txt, cs, and xml, split them into three seperate filters, and add an additional filter for _._

**Comment by ghost** [comment]
The Filter for the actual notepad would read like this:

```
Text Documents (*.txt)|*.txt|All Files (*.*)|*.*
```

**Comment by RPDevJesco** [comment]
Changed to reflect more along the lines of how Notepad would save the file.
